disabled_rules:
  - trailing_whitespace
  - vertical_whitespace
  - closure_parameter_position
  - vertical_parameter_alignment
  - statement_position
  - trailing_newline
  - function_body_length
  - type_body_length
  - variable_name
  # - shorthand_operator
  # - type_name
  - function_parameter_count
  - cyclomatic_complexity
  - nesting
  - implicit_getter # disabled because a mutating getter trigger the warning
  - opening_brace
  - class_delegate_protocol

opt_in_rules:
  - empty_count

empty_count: warning

trailing_whitespace:
  ignores_empty_lines: true

line_length: 130
file_length:
  warning: 1000
  error: 5000

large_tuple:
  warning: 4
  error: 4

# function_parameter_count: 
#   warning: 5
#   error: 10

excluded:
  - Pods/
